name: Ruby

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ["2.5", "2.6", "2.7", "3.0"]
    name: Ruby Test ${{ matrix.ruby }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache:
            true # Runs bundle install and caches gems. See the ruby_test.yml
            # example if you need more control over bundler.
      - name: Run tests
        run: bundle exec rspec
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache:
            true # Runs bundle install and caches gems. See the ruby_test.yml
            # example if you need more control over bundler.
      - name: Run lint
        run: bundle exec rubocop
